version: "3.9"

services:
  node_app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URI=mongodb://root:example@mongo_db:27017/mydb?authSource=admin
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db

  mongo_express:
    image: mongo-express:1.0.2
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo_db
    depends_on:
      - mongo_db

volumes:
  mongo_data:
